--1
SELECT A.ATTRACT_NAME,
	TP.PARK_NAME
FROM THEMEPARK TP
JOIN ATTRACTION A ON A.PARK_CODE = TP.PARK_CODE;
--2
SELECT A.ATTRACT_NAME,
	A.ATTRACT_CAPACITY
FROM THEMEPARK TP
JOIN ATTRACTION A ON A.PARK_CODE = TP.PARK_CODE
WHERE TP.PARK_NAME = 'FairyLand';
--3
SELECT E.EMP_FNAME,
	E.EMP_LNAME,
	A.ATTRACT_NAME,
	SUM(H.HOURS_PER_ATTRACT)
FROM EMPLOYEE E
JOIN HOURS H ON E.EMP_NUM = H.EMP_NUM
JOIN ATTRACTION A ON H.ATTRACT_NO = A.ATTRACT_NO
GROUP BY E.EMP_FNAME,
	E.EMP_LNAME,
	A.ATTRACT_NAME
ORDER BY E.EMP_FNAME;

--4 
SELECT TP.PARK_NAME,
	SUM(T.TICKET_PRICE)
FROM ATTRACTION A
JOIN THEMEPARK TP ON A.PARK_CODE = TP.PARK_CODE
JOIN TICKET T ON TP.PARK_CODE = T.PARK_CODE
WHERE T.TICKET_TYPE = 'Adult'
GROUP BY TP.PARK_NAME
ORDER BY TP.PARK_NAME;

--5
SELECT E.EMP_LNAME,
	E.EMP_AREA_CODE as EMP_AREACODE,
	E.EMP_PHONE,
	A.ATTRACT_NAME
FROM EMPLOYEE E
JOIN HOURS H ON E.EMP_NUM = H.EMP_NUM
JOIN ATTRACTION A ON H.ATTRACT_NO = A.ATTRACT_NO
WHERE H.DATE_WORKED = '2007-05-18'
ORDER BY A.ATTRACT_NAME DESC, E.EMP_LNAME ASC;

--6
SELECT TP.PARK_NAME,
	COUNT(T.TICKET_NO) AS TOTAL_TICKETS_SOLD
FROM THEMEPARK TP
JOIN TICKET T ON TP.PARK_CODE = T.PARK_CODE
GROUP BY TP.PARK_NAME
ORDER BY TP.PARK_NAME;
select * from employee;
select * from attraction;
--7 
SELECT E.*
FROM EMPLOYEE E
LEFT JOIN HOURS H ON E.EMP_NUM = H.EMP_NUM
WHERE H.EMP_NUM IS NULL;

--8
SELECT 
    E.EMP_NUM,
    E.EMP_LNAME,
    E.EMP_FNAME,
    E.EMP_HIRE_DATE,
    E.EMP_DOB,
    EXTRACT(YEAR FROM AGE(CURRENT_DATE, E.EMP_HIRE_DATE)) AS Length_of_Service
FROM EMPLOYEE E;


